using MemoryPack;
using Game.Action.Captures;
using Game.Action.Quiets;
using Game.Action.Skills;
using Game.Action.Relics;

namespace Game.Action
{
    // [MemoryPackUnion(0, typeof(DestroyConstruct))]
    // [MemoryPackUnion(1, typeof(FrenziedCapture))]
    // [MemoryPackUnion(2, typeof(FrenziedCaptureDontMove))]
    // [MemoryPackUnion(3, typeof(HorseLeechAttack))]
    // [MemoryPackUnion(4, typeof(IllusionCapture))]
    // [MemoryPackUnion(5, typeof(NormalCapture))]
    // [MemoryPackUnion(6, typeof(RemoraMark))]
    // [MemoryPackUnion(7, typeof(SnappingStrike))]
    // [MemoryPackUnion(8, typeof(EndTurn))]
    // [MemoryPackUnion(9, typeof(FlyingFishMove))]
    // [MemoryPackUnion(10, typeof(FrenziedMove))]
    // [MemoryPackUnion(11, typeof(NormalMove))]
    // [MemoryPackUnion(12, typeof(NormalSwap))]
    // [MemoryPackUnion(13, typeof(PegasusSeamothMove))]
    // [MemoryPackUnion(14, typeof(RemoraMove))]
    // [MemoryPackUnion(15, typeof(AdrenalineRadiatorExecute))]
    // [MemoryPackUnion(16, typeof(BlackPearlExecute))]
    // [MemoryPackUnion(17, typeof(ChaoticConstructorAction))]
    // [MemoryPackUnion(18, typeof(CommonPearlExecute))]
    // [MemoryPackUnion(19, typeof(CoralTomeAction))]
    // [MemoryPackUnion(20, typeof(CorruptedWisperExecute))]
    // [MemoryPackUnion(21, typeof(EyeOfMimicExecute))]
    // [MemoryPackUnion(22, typeof(FrostSigilExecute))]
    // [MemoryPackUnion(23, typeof(HermosHornExecute))]
    // [MemoryPackUnion(24, typeof(KelpBannerAction))]
    // [MemoryPackUnion(25, typeof(LedgerStoneExecute))]
    // [MemoryPackUnion(26, typeof(MangroveCharmExecute))]
    // [MemoryPackUnion(27, typeof(MethaneCasingExecute))]
    // [MemoryPackUnion(28, typeof(OrnetesEdictExecute))]
    // [MemoryPackUnion(29, typeof(OvergrownSlugAction))]
    // [MemoryPackUnion(30, typeof(PeaceTreatyExecute))]
    // [MemoryPackUnion(31, typeof(PrecisionMonocleAction))]
    // [MemoryPackUnion(32, typeof(RayStingerExecute))]
    // [MemoryPackUnion(33, typeof(ReliquaryExecute))]
    // [MemoryPackUnion(34, typeof(RottingScytheAction))]
    // [MemoryPackUnion(35, typeof(SeabedLevelerExecute))]
    // [MemoryPackUnion(36, typeof(SeafoamPhialAction))]
    // [MemoryPackUnion(37, typeof(SirenHarpoonExecute))]
    // [MemoryPackUnion(38, typeof(StormCapacitorExecute))]
    // [MemoryPackUnion(39, typeof(TemporalWarpExecute))]
    // [MemoryPackUnion(40, typeof(TimelessHourglassExecute))]
    // [MemoryPackUnion(41, typeof(AnglerfishTaunt))]
    // [MemoryPackUnion(42, typeof(AnomalocarisActive))]
    // [MemoryPackUnion(43, typeof(ArchelonShield))]
    // [MemoryPackUnion(44, typeof(ArcherfishActive))]
    // [MemoryPackUnion(45, typeof(ArcticBrittleStarActive))]
    // [MemoryPackUnion(46, typeof(BarnacleActive))]
    // [MemoryPackUnion(47, typeof(BlueDragonActive))]
    // [MemoryPackUnion(48, typeof(BobtailSquidActive))]
    // [MemoryPackUnion(49, typeof(BottlenoseDolphinActive))]
    // [MemoryPackUnion(50, typeof(ChamberedNautilusActive))]
    // [MemoryPackUnion(51, typeof(ChrysosUpgrade))]
    // [MemoryPackUnion(52, typeof(CutthroatEelActive))]
    // [MemoryPackUnion(53, typeof(DamselFishActive))]
    // [MemoryPackUnion(54, typeof(DiurnalActive))]
    // [MemoryPackUnion(55, typeof(DormantFossilAwake))]
    // [MemoryPackUnion(56, typeof(DwarfLionfishActive))]
    // [MemoryPackUnion(57, typeof(ElectricEelActive))]
    // [MemoryPackUnion(58, typeof(EpauletteSharkActive))]
    // [MemoryPackUnion(59, typeof(EyeshadeSculpinActive))]
    // [MemoryPackUnion(60, typeof(FlowerhornCichlidActive))]
    // [MemoryPackUnion(61, typeof(FlyingGurnardActive))]
    // [MemoryPackUnion(62, typeof(FrilledSharkActive))]
    // [MemoryPackUnion(63, typeof(GrenadiersActive))]
    // [MemoryPackUnion(64, typeof(GulperEelActive))]
    // [MemoryPackUnion(65, typeof(HatchetfishActive))]
    // [MemoryPackUnion(66, typeof(HermitCrabSwap))]
    // [MemoryPackUnion(67, typeof(HourglassJellyActive))]
    // [MemoryPackUnion(68, typeof(HumilitasActive))]
    // [MemoryPackUnion(69, typeof(LionfishActive))]
    // [MemoryPackUnion(70, typeof(LongSnoutedSeahorseActive))]
    // [MemoryPackUnion(71, typeof(MarineFlatwormActive))]
    // [MemoryPackUnion(72, typeof(MaskedPufferActive))]
    // [MemoryPackUnion(73, typeof(MegalodonActive))]
    // [MemoryPackUnion(74, typeof(PencilUrchinActive))]
    // [MemoryPackUnion(75, typeof(PhantomJellyActive))]
    // [MemoryPackUnion(76, typeof(PhronimaActive))]
    // [MemoryPackUnion(77, typeof(PistolShrimpActive))]
    // [MemoryPackUnion(78, typeof(PufferfishExplode))]
    // [MemoryPackUnion(79, typeof(RedtailParrotfishActive))]
    // [MemoryPackUnion(80, typeof(RibbonEelActive))]
    // [MemoryPackUnion(81, typeof(RustyParrotfishActive))]
    // [MemoryPackUnion(82, typeof(ScalyheadSculpinActive))]
    // [MemoryPackUnion(83, typeof(SeaStarResurrect))]
    // [MemoryPackUnion(84, typeof(SeaTurtleActive))]
    // [MemoryPackUnion(85, typeof(SirenActive))]
    // [MemoryPackUnion(86, typeof(SloaneViperfishActive))]
    // [MemoryPackUnion(87, typeof(SnaggletoothsActive))]
    // [MemoryPackUnion(88, typeof(SnipeEelActive))]
    // [MemoryPackUnion(89, typeof(SohalSurgeonfishActive))]
    // [MemoryPackUnion(90, typeof(StingrayDash))]
    // [MemoryPackUnion(91, typeof(SunfishActive))]
    // [MemoryPackUnion(92, typeof(SurgeWrasseActive))]
    // [MemoryPackUnion(93, typeof(SwordFishActive))]
    // [MemoryPackUnion(94, typeof(TemperantiaSwap))]
    // [MemoryPackUnion(95, typeof(ThalassosResurrect))]
    // [MemoryPackUnion(96, typeof(ThreadPipefishActive))]
    // [MemoryPackUnion(97, typeof(VelkarisKill))]
    // [MemoryPackUnion(98, typeof(SkipTurn))]
    // public abstract partial class Action
    // {
    // }
}
