namespace Game.Piece.PieceLogic.Commons
{
    public static class PieceFactory
    {
    public static PieceLogic CreateLogicInstance(string key, PieceConfig cfg)
        {
            return key switch
            {
                "piece_anglerfish" => new Anglerfish(cfg),
                "piece_anomalocaris" => new Anomalocaris(cfg),
                "piece_archelon" => new Archelon(cfg),
                "piece_archerfish" => new Archerfish(cfg),
                "piece_arctic_brittle_star" => new ArcticBrittleStar(cfg),
                "piece_armored_feather_star" => new ArmoredFeatherStar(cfg),
                "piece_barnacle" => new Barnacle(cfg),
                "piece_barracuda" => new Barracuda(cfg),
                "piece_bioluminescent_beacon" => new BioluminescentBeacon(cfg),
                "piece_black_swallower" => new BlackSwallower(cfg),
                "piece_blue_dragon" => new BlueDragon(cfg),
                "piece_bobtail_squid" => new BobtailSquid(cfg),
                "piece_bottlenose_dolphin" => new BottlenoseDolphin(cfg),
                "piece_brittle_star" => new BrittleStar(cfg),
                "piece_chambered_nautilus" => new ChamberedNautilus(cfg),
                "piece_chrysos" => new Chrysos(cfg),
                "piece_clown_fish" => new ClownFish(cfg),
                "piece_coffin_fish" => new CoffinFish(cfg),
                "piece_contagion_corpse" => new ContagionCorpse(cfg),
                "piece_electric_eel" => new ElectricEel(cfg),
                "piece_epaulette_shark" => new EpauletteShark(cfg),
                "piece_fangtooth" => new Fangtooth(cfg),
                "piece_feather_star" => new FeatherStar(cfg),
                "piece_flying_fish" => new FlyingFish(cfg),
                "piece_fracture_zone" => new FractureZone(cfg),
                "piece_grenadiers" => new Grenadiers(cfg),
                "piece_gulper_eel" => new GulperEel(cfg),
                "piece_hammer_oyster" => new HammerOyster(cfg),
                "piece_hatchetfish" => new Hatchetfish(cfg),
                "piece_helicoprion" => new Helicoprion(cfg),
                "piece_hermit_crab" => new HermitCrab(cfg),
                "piece_horseleech" => new HorseLeech(cfg),
                "piece_hourglass_jelly" => new HourglassJelly(cfg),
                "piece_humboldt_squid" => new HumboldtSquid(cfg),
                "piece_humilitas" => new Humilitas(cfg),
                "piece_kelp_bass" => new KelpBass(cfg),
                "piece_kelp_forest" => new KelpForest(cfg),
                "piece_lionfish" => new Lionfish(cfg),
                "piece_living_coral" => new LivingCoral(cfg),
                "piece_lizard_fish" => new Lizardfish(cfg),
                "piece_marine_iguana" => new MarineIguana(cfg),
                "piece_medicinal_leech" => new MedicinalLeech(cfg),
                "piece_megalodon" => new Megalodon(cfg),
                "piece_melibe" => new Melibe(cfg),
                "piece_moorish_idols" => new MoorishIdols(cfg),
                "piece_moray_eel" => new MorayEel(cfg),
                "piece_phantom_jelly" => new PhantomJelly(cfg),
                "piece_phronima" => new Phronima(cfg),
                "piece_pistol_shrimp" => new PistolShrimp(cfg),
                "piece_polluted_rock" => new PollutedRock(cfg),
                "piece_pufferfish" => new Pufferfish(cfg),
                "piece_remora" => new Remora(cfg),
                "piece_sea_star" => new SeaStar(cfg),
                "piece_sea_turtle" => new SeaTurtle(cfg),
                "piece_sea_urchin" => new SeaUrchin(cfg),
                "piece_seahorse" => new Seahorse(cfg),
                "piece_siren" => new GuidingSiren(cfg),
                "piece_slimehead" => new Slimehead(cfg),
                "piece_sloane's_viperfish" => new SloaneSViperfish(cfg),
                "piece_snaggletooths" => new Snaggletooths(cfg),
                "piece_snipe_eel" => new SnipeEel(cfg),
                "piece_spider_brittle_star" => new SpiderBrittleStar(cfg),
                "piece_stingray" => new Stingray(cfg),
                "piece_stonecrab" => new StoneCrab(cfg),
                "piece_sunfish" => new Sunfish(cfg),
                "piece_swordfish" => new Swordfish(cfg),
                "piece_temperantia" => new Temperantia(cfg),
                "piece_thalassos" => new Thalassos(cfg),
                "piece_tiger_prawn" => new TigerPrawn(cfg),
                "piece_velkaris" => new Velkaris(cfg),
                _ => null
            };
        }
    }
}
